apiVersion: v1
kind: Secret
metadata:
  name: pedido-backend-db-secret
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  password: {{ .Values.postgresql.auth.password | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
  database: {{ .Values.postgresql.auth.database | quote }}