apiVersion: v2
name: pedido-app
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: postgresql
    version: 15.5.20
    repository: "https://charts.bitnami.com/bitnami"

